### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by rwunsch**
add error-handling for "error" and "warn" API responses.

I think [PR#10](https://github.com/jjbankert/hass_chatgpt/pull/10) could be rejected if this is accepted, as it would duplicate the debug response.

### CODE REVIEW

**Comment by rwunsch** [comment]
I think we should be also throwing an EXCEPTION on ERROR and WARN ... but I do not know how to do that yet.

Something like this:
https://developers.home-assistant.io/docs/integration_fetching_data

(and possibly make the request async, as described in the link above).

I attempted to add a first try-catch-block and tested the if-else and try-catch, which at least did still "work" in my environment:
image

**Comment by jjbankert** [comment]
I'll hopefully have time to look at this over the next days.

**Comment by jjbankert** [comment]
@rwunsch I'm discontinuing the project because my personal use-cases are now covered by the latest Home Assistant release. See the README for my suggested migration option. Of course you can always continue running a fork of my repo with your patch. Thanks for the effort you put into this!

**Comment by rwunsch** [comment]
Thanks @jjbankert !
I was not aware of the change and will check how you changed to OOTB HA functionality.
Thanks for this repo anyway!

**Pull request closed without merging**
