### PR TITLE
Update __init__.py with some logging

### PR DESCRIPTION
**Pull request by rwunsch**
adding some logging to see the response in the logs as info.

### CODE REVIEW

**Comment by jjbankert** [comment]
Thanks for the pull request and letting me know about issue #9! I think we can be a bit more precise by only logging the errors and/or logging normal operations as `debug` rather than `info`

**Review by rwunsch — COMMENTED** [review]
I have changed the logging from INFO to DEBUG.
Makes sense.

**Comment by jjbankert** [comment]
Weirdly enough I can't find a dedicated page that documents logging for HA. The example on [this page ](https://developers.home-assistant.io/docs/dev_101_states?_highlight=logging#using-states-in-your-component) looks a bit different than what you wrote though. 

I haven't tried your code yet, but I suspect that it doesn't write the component name in the message right now. And it should automagically do that when defining the logger like that example.

Also, it's probably a good thing to split out the error messages and log that as `logger.error` level. I'll look up the documentation for openAI errors.

**Review by rwunsch — COMMENTED** [review]
use _LOGGER proxy code for logger.

This is what the log-message looks like now (after enabling the HA-logger on DEBUG):
image

```
configuration.yaml:
logger:
  default: info
  logs:
    custom_components.chatgpt: debug
```

I think checking on the openAI-API errors, and catching them is a good idea! :) 
Link: https://platform.openai.com/docs/guides/error-codes/api-errors

**Comment by rwunsch** [comment]
I would be closing this PR in favor of PR#11.

**Pull request closed without merging**
