### PR TITLE
Fix requests version conflict

### LINKED ISSUE #6: Stopped working on Homeassistant 2023.6
> Package chatgpt setup failed. Component chatgpt Requirements for chatgpt not found: ['requests==2.28.2'].

### PR DESCRIPTION
**Pull request by TNTLarsn**
Update requests to 2.31.0

https://github.com/home-assistant/core/pull/93363

fix https://github.com/jjbankert/hass_chatgpt/issues/6

### CODE REVIEW

**Comment by johnwalk61** [comment]
Change fixed the issue

**Comment by aceindy** [comment]
Looks like it does fix it...

The original issue with HA 2023.6.0:
image

**Comment by antisane** [comment]
I've had this working for a few weeks now, but now Home Assistant does not like the confuration.yaml entry at all. 
If I remove it I can reboot HAOS with no issues, but if I put it back (the way it worked before) I get an invalid config entry error and cannot restart Home Assistant.

**Comment by jjbankert** [comment]
Whoops!

Will the updated version still work with 2023.5 after this change? I would expect something like `requests>=2.28.2` to be more robust

**Comment by jjbankert** [comment]
Thanks for finding the root of the problem. Made my life very easy :)

**Pull request merged**
